je-me-presente/config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'contact', to: 'static_pages#contact', as: 'pinkphone'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'about/toi', to: 'static_pages#about_toi', as: 'aboutme'
  get 'about/ton_group', to: 'static_pages#about_ton_group', as: 'aboutus'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

je-me-presente/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

je-me-presente/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

je-me-presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def about_toi
  end

  def about_ton_group
  end
end

je-me-presente/app/helpers/application_helper.rb
module ApplicationHelper
end

je-me-presente/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

je-me-presente/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

je-me-presente/app/views/static_pages/about.html.erb
<h1>About Love</h1>
<h2>Hello, never forget :</h2>
  <p>Love is the most beautiful thing in the world, never forget it and never sacrifice your love for some professionnel stuffs.</p>
<p> Si tu veux mieux me connaître <a href= "<%= aboutme_path %>" title="la suite par ici" target=>clique ici</a> <br>
 Si tu veux mieux connaître mon groupe <a href="<%= aboutus_path %>" title="notre suite par ici" target=>clique ici</a></p>

je-me-presente/app/views/static_pages/about_toi.html.erb
<h1> David Coat</h1>

<p>Salut, je suis un petit nouveau en programation et moi plus grand plaisir est d'apprendre.<br>
  Allez viens! apprenons ensemble </p>

je-me-presente/app/views/static_pages/about_ton_group.html.erb
<h1>Elonmusk Crew</h1>

<p>Bienvenu sur notre premier site.<br>
Composé de Mohammad-Ali, Odyssée, Hogo et David, nous sommes le dernier groupe survivant de Lyon.<br>
Notre mentalité est simple : "Nous pouvons réussir tout ce que nous entreprenons, nous abandonnerons jamais peu importe les défis sur notre route". </p>

je-me-presente/app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p> For more information, contact me by: <br>
mail : liveyourlive@gmail.com<br>
phone : 0809653544</p>

je-me-presente/app/views/static_pages/home.html.erb
<h1>Welcome my friend</h1>
<p>Come to the world where you can be better</p>