white_rabbit/config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home' #Ici avec "root" nous avons la position de la page principal qui aura comme adresse le localhost:3000
  get 'user', to: 'users#new', as: 'useme'#Pour ces get et post, nous indiquons 1-le nom qui sera dans la barre d'adresse
  post '/', to: 'users#create', as: 'usercreate'# avec le to: c'est le chemin vers la métode lié à la page
  get 'user/user_id', to: 'users#show', as: 'showtime'# et avec le as: c'est le surnom de ce chemin 

end

white_rabbit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

white_rabbit/app/models/user.rb
class User < ApplicationRecord
end

white_rabbit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

white_rabbit/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

white_rabbit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new #Ici nous créons un nouvel utilisateur qui aura les caractéristiques récupéré dans les parametres après que l'utilisateur les ai soumis.
    user.user_name = params["user_name"]
    user.bio = params["user_text"]
    user.save
    redirect_to showtime_path
  end

  def show
    @id = User.last #ici nous récupérons les dernières données entrée dans la database
  end
end

white_rabbit/app/helpers/application_helper.rb
module ApplicationHelper
end

white_rabbit/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

white_rabbit/app/helpers/users_helper.rb
module UsersHelper
end

white_rabbit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiteRabbit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

white_rabbit/app/views/static_pages/home.html.erb
<h1>Bienvenue sur ma page d'accueil</h1>
<p>Cher utilisateur, si vous désirez vous inscrire veuillez <a href= "<%= useme_path %>" title="s'inscrire ici" target=>clique ici</a> </p>

white_rabbit/app/views/users/new.html.erb
<h2>Inscription</h2>
<p>Veuillez préciser votre prénom et vous d'écrire pour vous inscrire</p>

<form action="/" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Prénom:<br>
  <input type="text" name="user_name">
  <br>
  Description:<br>
  <textarea rows="4" cols="50" name="user_text">

  </textarea>
  <br><br>
  <input type="submit" value="S'inscrire">
</form>

white_rabbit/app/views/users/show.html.erb
<h1>Bienvenue parmis nous <%= @id.user_name %></h1> 
<h2>Nous garderons toujours en mémoire ta description</h2>
<p> <%= @id.bio %></p>